networks:
  squiglink:
    name: squiglink

services:
  api:
    build: .
    depends_on:
      - postgres
    environment:
      - SQUIGLINK_POSTGRES_DATABASE=squiglink_dev
      - SQUIGLINK_POSTGRES_HOST=postgres
      - SQUIGLINK_POSTGRES_PASSWORD=postgres
      - SQUIGLINK_POSTGRES_TEST_DATABASE=squiglink_test
      - SQUIGLINK_POSTGRES_USER=postgres
      # JWT_SECRET should be a random string, you can generate one with `openssl rand -hex 32`
      - JWT_SECRET=change_me
      - RESEND_API_KEY=change_me
      - AUTH_EMAIL=no-reply@example.com
      - APP_URL=http://localhost:3000
    networks:
      - squiglink
    ports:
      - 3000:3000
    volumes:
      - .:/api

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:17.2-alpine3.21
    networks:
      - squiglink
    ports:
      - 5432:5432
    volumes:
      - ./docker/entrypoint.sql:/docker-entrypoint-initdb.d/entrypoint.sql
