[package]
name = "squiglink_api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
postgres-types = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
