name: Check

on:
  push:

jobs:
  check-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cp .env.example .env
      - run: docker build --tag ghcr.io/${{ github.repository }}:latest --target production .
      - run: docker compose --file compose.production.yaml up postgres --wait
      - run: docker compose --file compose.production.yaml run --rm server task database-create
      - run: docker compose --file compose.production.yaml run --rm server task kysely -- migrate:latest
      - run: docker compose --file compose.production.yaml up --wait
      - run: curl --silent http://127.0.0.1:3000/health
      - run: docker compose --file compose.production.yaml down

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: go-task/setup-task@v1
      - run: cp .env.example .env
      - run: export $(sed 's/#.*//' .env)
      - run: task install-dependencies
      - run: task database-create-test
      - run: task kysely-test -- migrate:latest
      - run: task check
